name: myenv  # Replace 'myenv' with your preferred environment name
channels:
  - defaults
dependencies:
  - python=3.10  # Replace with your desired Python version
  - numpy
  - matplotlib
  - librosa
  - moviepy
  - pytorch
  - torchvision
  - pillow
  - tqdm
  - pytorch_pretrained_biggan
  - scipy==1.1.0
