name: Visualize Audio with BigGAN

on:
  push:
    paths:
      - 'visualize.py'
      - 'requirements.txt'
      - 'beethoven.mp3'

jobs:
  visualize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create Conda environment
      run: |
        conda env create -f environment.yml
        conda activate <your_environment_name>

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Execute visualization script
      run: |
        python visualize.py --song beethoven.mp3 --output_file output.mp4

    - name: Upload video artifact
      uses: actions/upload-artifact@v2
      with:
        name: visualization-artifact
        path: output.mp4
